# Railway/Nixpacks Configuration
# Forces Node.js 20 (required for Solana/Drift packages)
# Includes Python and build tools for native modules (usb, etc.)

[phases.setup]
nixPkgs = ["nodejs_20", "openssl", "python3", "gcc", "gnumake", "pkg-config", "libudev-zero"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

