# Railway/Nixpacks Configuration
# Forces Node.js 20 (required for Solana/Drift packages)
# Skip optional native modules to avoid USB compilation issues

[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = [
  "npm install --legacy-peer-deps --omit=optional"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm run start"

