# Railway Configuration File
# Defines how to build and run your services
# Build is handled by nixpacks.toml

[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Health check
healthcheckPath = "/api/health"
healthcheckTimeout = 10

[services.web]
# Next.js application
startCommand = "npm run start"

[services.websocket]
# WebSocket server
startCommand = "npm run start:ws"

[services.worker]
# Background sync worker
startCommand = "npm run start:worker"

